### ISSUE TITLE
Fatal error when running in Console app (CLI) 

### ISSUE THREAD

**Issue by stevenrhiggins** [stefanorg/JHttps#1]
Loving this module.

On running a console app with JHttps installed, I received the following error

Fatal error: Call to undefined method Zend\Mvc\Router\Console\SimpleRouteStack::getRequestUri() in ..../vendor/JHttps/src/JHttps/Listeners/JHttpsRouteListener.php on line 41

I hacked JHttpsRouteListener.php adding the follwing to the preDispatch method:

$request = $e->getRequest();
if ( method_exists($request, 'getServer') ){
   // dispatch block
}

**Comment by stefanorg** [comment]
thanks. Now should be fixed, can you give me some feedback ?

**Comment by stevenrhiggins** [comment]
Working perfectly now! Thanks much for your very fast response!

**Comment by stefanorg** [comment]
;)
